services:
  collector:
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8090"
    volumes:
      - ./collector/collector.yaml:/etc/otelcol-contrib/config.yaml

  prometheus:
    image: prom/prometheus:latest
    command:
      - "--enable-feature=remote-write-receiver"
      - "--enable-feature=otlp-write-receiver"
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-enterprise
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/gno-dashboards.json:/var/lib/grafana/dashboards/gno-dashboards.json
    ports:
      - "3000:3000"

  gnoland:
    image: ghcr.io/gnolang/gno/gnoland:master
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    ports:
      - "26657:26657"
      - "26660:26660"
    volumes:
      - ./gnoland/entrypoint.sh:/entrypoint.sh

  supernova:
    image: ghcr.io/gnolang/supernova
    command: >
      -sub-accounts 10 -transactions 200 -url http://gnoland:26657
      -mnemonic "source bonus chronic canvas draft south burst lottery vacant surface solve popular case indicate oppose farm nothing bullet exhibit title speed wink action roast"
    restart: always
    depends_on:
      - gnoland
